'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace AdaptiveSlideNavigation.UserControls


    Partial Public Class Navigation

        ''' <summary>
        ''' NavigationBreadCrumbsButton control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected NavigationBreadCrumbsButton As Global.DevExpress.Web.ASPxButton

        ''' <summary>
        ''' NavigationTreeView control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected NavigationTreeView As Global.DevExpress.Web.ASPxTreeView

        ''' <summary>
        ''' XmlDataSource1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected XmlDataSource1 As Global.System.Web.UI.WebControls.XmlDataSource
    End Class
End Namespace
