'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Namespace AdaptiveSlideNavigation.UserControls


    Partial Public Class Search

        ''' <summary>
        ''' XmlDataSource1 control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected XmlDataSource1 As Global.System.Web.UI.WebControls.XmlDataSource

        ''' <summary>
        ''' searchResults control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected searchResults As Global.DevExpress.Web.ASPxCallbackPanel

        ''' <summary>
        ''' SearchResultsNavBar control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected SearchResultsNavBar As Global.DevExpress.Web.ASPxNavBar

        ''' <summary>
        ''' noResultsContainer control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected noResultsContainer As Global.System.Web.UI.HtmlControls.HtmlGenericControl

        ''' <summary>
        ''' requestText control.
        ''' </summary>
        ''' <remarks>
        ''' Auto-generated field.
        ''' To modify move field declaration from designer file to code-behind file.
        ''' </remarks>
        Protected requestText As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    End Class
End Namespace
